version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test

  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build && npx semantic-release


workflows:
  test:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: main
